"""create user and blog tables

Revision ID: 7df50a94a2ff
Revises: af57bf9aad8c
Create Date: 2024-03-05 12:35:54.024989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df50a94a2ff'
down_revision = 'af57bf9aad8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
